services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: delayed-notifier-app
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      redis:
        condition: service_started
    ports:
      - "8080:8080"
    environment:
      - CONFIG_PATH=./config/local.yaml
    networks:
      - notifier-network

  db:
    image: postgres:15-alpine
    container_name: notifier-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: notifier
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d notifier"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - notifier-network

  db-migrator:
    image: migrate/migrate
    container_name: notifier-db-migrator
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    volumes:
      - ./migrations:/migrations:ro
    command:
      - "-path"
      - "/migrations"
      - "-database"
      - "postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=${DB_SSL_MODE}"
      - "up"
    restart: "no"

  redis:
    image: redis:7-alpine
    container_name: notifier-redis
    command:
      [
        "redis-server",
        "--maxmemory",
        "100mb",
        "--maxmemory-policy",
        "allkeys-lru",
      ]
    ports:
      - "6379:6379"
    networks:
      - notifier-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: notifier-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - notifier-network

networks:
  notifier-network:
    driver: bridge
